### ISSUE TITLE
Nugget Support

### ISSUE THREAD

**Issue by noelzappy** [tryfoobar/react-native-commandbar#4]
Does this package support nuggets? If so how do I use it, it seems the HelpHub is all I can see.
@Cavallando

**Comment by Cavallando** [comment]
Hey @noelzappy! We currently only support HelpHub and Copilot in our Mobile SDKs, [Nudges](https://www.commandbar.com/docs/guides/nudge-experiences/nudges-overview/) are only supported in our Web SDK currently
